name: Issue Comment Bot
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment for bug
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it'
            })
      - name: Add comment for feature
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature.'
            })
      - name: Add generic comment
        if: github.event.issue.labels.length == 0
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for your contribution!'
            })
